version: '3.4'

# x-cache-from:
#   - &api-cache-from
#     cache_from:
#       - ${NGINX_IMAGE:-music_gether/nginx}
#       - ${PHP_IMAGE:-music_gether/php}

services:
  php:
    build:
      context: ./
      target: music_gether_php
      # <<: *api-cache-from
    # image: music_gether_php
    # healthcheck:
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 30s
    depends_on:
      - db
      # - dev-tls
    volumes:
      - ./:/srv/api:rw,cached
      - ./var:/srv/api/var
      - ./docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
  
  api:
    build:
      context: ./
      target: music_gether_nginx
      # <<: *api-cache-from
    # image: music_gether_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro
    ports:
      - 8080:80

  # nginx:
  #   image: nginx:1.17-alpine
  #   restart: on-failure
  #   depends_on: 
  #     - php
  #   volumes:
  #     - ./public:/srv/api/public
  #     - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - 80:8080
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - db-data:/var/lib/mysql
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - target: 3306
        published: 3306
        protocol: tcp

volumes:
  db-data: {}