#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create_concert:
    path: /concerts
    # the controller value has the format 'controller_class::method_name'
    controller: App\Concert\Controller\CreateConcertController
    methods:    POST

get_concerts:
    path: /concerts
    controller: App\Concert\Controller\GetConcertsController
    methods:    GET

create_user:
    path: /users
    controller: App\User\Controller\CreateUserController
    methods:    POST

get_users:
    path: /users
    controller: App\User\Controller\GetUsersController
    methods:    GET