#index:
#    path: /
#    controller: App\Controller\DefaultController::index

## CONCERT ##
create_concert:
    path: /concerts
    # the controller value has the format 'controller_class::method_name'
    controller: App\Concert\Controller\CreateConcertController
    methods:    POST

get_concerts:
    path: /concerts
    controller: App\Concert\Controller\GetConcertsController
    methods:    GET

get_concert_by_id:
    path: /concerts/{id}
    controller: App\Concert\Controller\GetConcertByIdController
    methods:    GET

update_concert_by_id:
    path: /concerts/{id}
    controller: App\Concert\Controller\UpdateConcertByIdController
    methods:    PUT

## USER ##
create_user:
    path: /users
    controller: App\User\Controller\CreateUserController
    methods:    POST

get_user_by_id:
    path: /users/{id}
    controller: App\User\Controller\GetUserByIdController
    methods:    GET

get_users:
    path: /users
    controller: App\User\Controller\GetUsersController
    methods:    GET

update_user_by_id:
    path: /users/{id}
    controller: App\User\Controller\UpdateUserByIdController
    methods:    PUT