#index:
#    path: /
#    controller: App\Controller\DefaultController::index

create_concert:
    path: /concerts
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\Concert\CreateConcertController
    methods:    POST

get_concerts:
    path: /concerts
    controller: App\Concert\Controller\GetConcertsController
    methods:    GET

create_user:
    path: /users
    controller: App\Controller\User\CreateUserController
    methods:    POST

get_users:
    path: /users
    controller: App\Controller\User\GetUsersController
    methods:    GET